### PR TITLE
Testing PRs

### PR DESCRIPTION
**Pull request by xuanxu**
---
name: Software submission Pull Request
about: Use this template to submit software for review as a PR
title: ''
labels: ''
assignees: ''

---

Submitting Author: AUTHOR_NAME (@AUTHOR_GITHUB_HANDLE)  
Repository: URL_OF_THE_SOFTWARE_REPO  
Version submitted: VERSION 

  
Editor: @gemgon  
Reviewer 1: TBD  
Reviewer 2: @gemgon  
Archive: TBD  
Version accepted: v1.3.6  
Reviewers: @xuanxu  

---

## Description 

```
Testing bot acting on PRs
```

## Scope 

- Please indicate which category or categories this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] geospatial data
	- [ ] text analysis
	
- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

## Technical checks

Confirm each of the following by checking the box.  
This package:

- [ ] does not violate the Terms of Service of any service it interacts with. 
- [ ] has a CRAN and OSI accepted license.
- [ ] contains a README with instructions for installing the development version.
- [ ] includes documentation.
- [ ] has a test suite.
- [ ] has continuous integration.

## Code of conduct

- [ ] I agree to abide by our Code of Conduct during the review process and in maintaining my package should it be accepted.

### CODE REVIEW

**Comment by xuanxu** [comment]
hello @botsci

**Comment by botsci** [comment]
Hi!

**Comment by xuanxu** [comment]
@botsci help

**Comment by botsci** [comment]
Hello @xuanxu, here are the things you can ask me to do:

```

# List all available commands
@botsci help

# Show our Code of Conduct
@botsci code of conduct

# Add a user to this issue's reviewers list
@botsci add xxxxx to reviewers

# Remove a user from the reviewers list
@botsci remove xxxxx from reviewers

```

**Comment by xuanxu** [comment]
@botsci code of conduct

**Comment by botsci** [comment]
Our Code of Conduct can be found at https://ropensci.org

**Comment by xuanxu** [comment]
@botsci help

**Comment by botsci** [comment]
Hello @xuanxu, here are the things you can ask me to do:

```

# List all available commands
@botsci help

# Show our community Code of Conduct and Guidelines
@botsci code of conduct

# List all current topic editors
@botsci list editors

# Assign a user as the reviewer N of this submission (where N=1,2...)
@botsci assign @username as reviewer 2

# Remove the user assigned as reviewer N of this submission (where N=1,2...)
@botsci remove reviewer 2

# Add to this issue's reviewers list
@botsci add @username to reviewers

# Remove from this issue's reviewers list
@botsci remove @username from reviewers

# Assign a user as the editor of this submission
@botsci assign @username as editor

# Remove the editor assigned to this submission
@botsci remove editor

# Send an invitation to a user to collaborate in the review
@botsci invite @username

# Add a user to this issue's assignees list
@botsci add assignee: @username

# Remove a user from this issue's assignees list
@botsci remove assignee: @username

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@botsci check references
@botsci check references from custom-branch-name

# Perform checks on the repository
# Optionally, it can be run on a non-default branch 
@botsci check repository
@botsci check repository from custom-branch-name

# Set a value for version
@botsci set v1.0.0 as version

# Set a value for archive
@botsci set 10.21105/joss.12345 as archive

# Label issue with: reviewed, recommend publication, pending publication. Remove labels: ongoing, pending review
@botsci review successful

# Label issue with: recommend rejection
@botsci review failed

# Close the issue
@botsci reject

# Reports on the quality of the code
@botsci analyze code

# Random facts about cats
@botsci tell me something about cats

# Add review checklist for a user
@botsci add checklist for @username

# Remove the checklist for a user
@botsci remove checklist for @username

```

**Comment by xuanxu** [comment]
@botsci set v1.2.3 as version

**Comment by botsci** [comment]
Done! version is now v1.2.3

**Comment by xuanxu** [comment]
@botsci review successful

**Comment by xuanxu** [comment]
@botsci help

**Comment by botsci** [comment]
Hello @xuanxu, here are the things you can ask me to do:

```

# List all available commands
@botsci help

# Show our community Code of Conduct and Guidelines
@botsci code of conduct

# List all current topic editors
@botsci list editors

# Assign a user as the reviewer N of this submission (where N=1,2...)
@botsci assign @username as reviewer 2

# Remove the user assigned as reviewer N of this submission (where N=1,2...)
@botsci remove reviewer 2

# Add to this issue's reviewers list
@botsci add @username to reviewers

# Remove from this issue's reviewers list
@botsci remove @username from reviewers

# Assign a user as the editor of this submission
@botsci assign @username as editor

# Remove the editor assigned to this submission
@botsci remove editor

# Send an invitation to a user to collaborate in the review
@botsci invite @username

# Add a user to this issue's assignees list
@botsci add assignee: @username

# Remove a user from this issue's assignees list
@botsci remove assignee: @username

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@botsci check references
@botsci check references from custom-branch-name

# Perform checks on the repository
# Optionally, it can be run on a non-default branch 
@botsci check repository
@botsci check repository from custom-branch-name

# Set a value for version
@botsci set v1.0.0 as version

# Set a value for archive
@botsci set 10.21105/joss.12345 as archive

# Label issue with: reviewed, recommend publication, pending publication. Remove labels: ongoing, pending review
@botsci review successful

# Label issue with: recommend rejection
@botsci review failed

# Close the issue
@botsci reject

# Reports on the quality of the code
@botsci analyze code

# Random facts about cats
@botsci tell me something about cats

# Add review checklist for a user
@botsci add checklist for @username

# Remove the checklist for a user
@botsci remove checklist for @username

```

**Comment by xuanxu** [comment]
@botsci assign @gemgon as reviewer 2

**Comment by xuanxu** [comment]
@botsci add @xuanxu to reviewers

**Comment by botsci** [comment]
@xuanxu added to the reviewers list!

**Comment by xuanxu** [comment]
@botsci set v1.3.6 as version

**Comment by botsci** [comment]
Done! version is now v1.3.6

**Comment by xuanxu** [comment]
@botsci tell me something about cats

**Comment by botsci** [comment]
Error (503). The cat_facts service is currently unavailable

**Comment by xuanxu** [comment]
@botsci analyze code

**Comment by botsci** [comment]
Inspecting code...

**Comment by botsci** [comment]
The quality of the code in URL_OF_THE_SOFTWARE_REPO is really bad

**Comment by xuanxu** [comment]
@botsci assign @gemgon as reviewer 1

**Comment by xuanxu** [comment]
@botsci assign @gemgon as reviewer 1

**Comment by xuanxu** [comment]
@botsci assign @gemgon as reviewer 2

**Comment by xuanxu** [comment]
@botsci assign @gemgon as editor

**Comment by botsci** [comment]
Assigned! @gemgon is now the editor

**Comment by xuanxu** [comment]
@botsci assign @gemgon as reviewer 2

**Comment by botsci** [comment]
Reviewer 2 assigned!

**Review by xuanxu — COMMENTED** [review]
@botsci thanks!

**Pull request closed without merging**
